SCRIPT_ROOT = PIPELINE_ROOT / "scripts"

SCRIPT_QC = str(SCRIPT_ROOT / "qc.py")
SCRIPT_REFERENCE = str(SCRIPT_ROOT / "reference.py")
SCRIPT_PREDICT = str(SCRIPT_ROOT / "predict.py")
SCRIPT_RUNTIME = str(SCRIPT_ROOT / "runtime.py")

SCRIPT_BATCH_BAM_UNIFORMITY_QC = SCRIPT_QC
SCRIPT_BATCH_BAM_UNIFORMITY_QC_ACTION = "batch_bam_uniformity_qc"
SCRIPT_AGGREGATE_BASELINE_QC = SCRIPT_QC
SCRIPT_AGGREGATE_BASELINE_QC_ACTION = "aggregate_baseline_qc"
SCRIPT_BASELINE_QC_REPORT = SCRIPT_QC
SCRIPT_BASELINE_QC_REPORT_ACTION = "baseline_qc_report"
SCRIPT_RUN_QC_FRAMEWORK = SCRIPT_QC
SCRIPT_RUN_QC_FRAMEWORK_ACTION = "run_qc_framework"

SCRIPT_BUILD_BIN_ANNOTATIONS = SCRIPT_REFERENCE
SCRIPT_BUILD_BIN_ANNOTATIONS_ACTION = "build_bin_annotations"
SCRIPT_BUILD_FROZEN_REFERENCE_PACKAGE = SCRIPT_REFERENCE
SCRIPT_BUILD_FROZEN_REFERENCE_PACKAGE_ACTION = "build_frozen_reference_package"

SCRIPT_CNV_CORRECTION = SCRIPT_PREDICT
SCRIPT_CNV_CORRECTION_ACTION = "cnv_correction"
SCRIPT_CNV_CALLING = SCRIPT_PREDICT
SCRIPT_CNV_CALLING_ACTION = "cnv_calling"
SCRIPT_CNV_CALIBRATION = SCRIPT_PREDICT
SCRIPT_CNV_CALIBRATION_ACTION = "cnv_calibration"
SCRIPT_CNV_MOSAIC_FRACTION = SCRIPT_PREDICT
SCRIPT_CNV_MOSAIC_FRACTION_ACTION = "cnv_mosaic_fraction"
SCRIPT_CNV_ARTIFACT_RULES = SCRIPT_PREDICT
SCRIPT_CNV_ARTIFACT_RULES_ACTION = "cnv_artifact_rules"
SCRIPT_CNV_ML = SCRIPT_PREDICT
SCRIPT_CNV_ML_ACTION = "cnv_ml"
SCRIPT_CNV_EVALUATION = SCRIPT_PREDICT
SCRIPT_CNV_EVALUATION_ACTION = "cnv_evaluation"
SCRIPT_CNV_BENCHMARK = SCRIPT_PREDICT
SCRIPT_CNV_BENCHMARK_ACTION = "cnv_benchmark"
SCRIPT_CNV_REPORT = SCRIPT_PREDICT
SCRIPT_CNV_REPORT_ACTION = "cnv_report"

SCRIPT_VALIDATE_FRACTION_TRUTH = str(SCRIPT_ROOT / "validation.py")
SCRIPT_VALIDATE_FRACTION_TRUTH_ACTION = "validate_fraction_truth"

SCRIPT_COLLECT_BENCHMARKS_TO_SQLITE = SCRIPT_RUNTIME
