ALL_TARGET_FILES = []
BASELINE_QC_TARGET_FILES = []
REFERENCE_QC_TARGET_FILES = []
REFERENCE_ASSET_TARGET_FILES = []
REFERENCE_PACKAGE_TARGET_FILES = []
QC_FRAMEWORK_TARGET_FILES = []
RUNTIME_BENCHMARK_FILES = []
if "mapping" in REQUESTED_TARGETS:
    ALL_TARGET_FILES += expand(SORTED_BAM, sample=SAMPLES) + expand(SORTED_BAI, sample=SAMPLES)
    RUNTIME_BENCHMARK_FILES += expand(BENCH_FASTP_BWA, sample=SAMPLES)
if "metadata" in REQUESTED_TARGETS:
    ALL_TARGET_FILES.append(RUN_METADATA)
if "baseline_qc" in REQUESTED_TARGETS:
    BASELINE_QC_TARGET_FILES += [
        BASELINE_QC_SUMMARY,
        BASELINE_QC_PASS_SAMPLES,
        BASELINE_QC_RETAINED_SAMPLES,
        BASELINE_QC_OUTLIER_SAMPLES,
        BASELINE_QC_REPORT_MD,
        BASELINE_QC_FIG_DECISION,
        BASELINE_QC_FIG_MAPPED,
        BASELINE_QC_FIG_METRICS,
        BASELINE_QC_FIG_BATCH,
        BASELINE_QC_FIG_CORR,
    ]
    BASELINE_QC_TARGET_FILES += [
        BASELINE_MULTI_BINSIZE_SUMMARY,
        BASELINE_MULTI_SAMPLE_MATRIX,
        BASELINE_MULTI_STABLE_RETAINED,
        BASELINE_MULTI_FAILED_DIAG,
        BASELINE_REPORT_MD,
        BASELINE_MULTI_FIG_DECISION_TREND,
        BASELINE_MULTI_FIG_SAMPLE_HEATMAP,
        BASELINE_MULTI_FIG_LIBRARY,
        BASELINE_MULTI_FIG_FAIL_CHROM,
    ]
    BASELINE_QC_TARGET_FILES += expand(BASELINE_FLAGSTAT, sample=BASELINE_SAMPLE_IDS)
    BASELINE_QC_TARGET_FILES += expand(BASELINE_IDXSTATS, sample=BASELINE_SAMPLE_IDS)
    for bin_label in BASELINE_QC_BIN_LABELS:
        BASELINE_QC_TARGET_FILES += [
            BASELINE_MULTI_SUMMARY.format(bin_label=bin_label),
            BASELINE_MULTI_PASS_SAMPLES.format(bin_label=bin_label),
            BASELINE_MULTI_RETAINED_SAMPLES.format(bin_label=bin_label),
            BASELINE_MULTI_OUTLIER_SAMPLES.format(bin_label=bin_label),
            BASELINE_MULTI_REPORT_MD.format(bin_label=bin_label),
            BASELINE_MULTI_FIG_DECISION.format(bin_label=bin_label),
            BASELINE_MULTI_FIG_MAPPED.format(bin_label=bin_label),
            BASELINE_MULTI_FIG_METRICS.format(bin_label=bin_label),
            BASELINE_MULTI_FIG_BATCH.format(bin_label=bin_label),
            BASELINE_MULTI_FIG_CORR.format(bin_label=bin_label),
        ]
    ALL_TARGET_FILES += BASELINE_QC_TARGET_FILES
    REFERENCE_ASSET_TARGET_FILES += [
        REFERENCE_ATOMIC_BINS,
        REFERENCE_ANALYSIS_BINS,
        REFERENCE_QC_BINS,
        REFERENCE_ATOMIC_BIN_ANNOTATIONS,
        REFERENCE_ANALYSIS_BIN_ANNOTATIONS,
        REFERENCE_QC_BIN_ANNOTATIONS,
        REFERENCE_BIN_SUMMARY_JSON,
        REFERENCE_HARD_MASK_TSV,
        REFERENCE_SOFT_MASK_TSV,
        REFERENCE_DYNAMIC_MASK_TSV,
        REFERENCE_COMBINED_MASK_TSV,
        REFERENCE_HARD_MASK_JSON,
        REFERENCE_SOFT_MASK_JSON,
        REFERENCE_DYNAMIC_MASK_JSON,
        REFERENCE_COMBINED_MASK_JSON,
        REFERENCE_MASK_SUMMARY_JSON,
    ]
    QC_FRAMEWORK_TARGET_FILES += [
        RUN_QC_TSV,
        RUN_QC_JSON,
        SAMPLE_QC_TSV,
        SAMPLE_QC_JSON,
        BIN_QC_TSV,
        BIN_QC_JSON,
        EVENT_QC_TSV,
        EVENT_QC_JSON,
        QC_FRAMEWORK_FIG_SAMPLE,
        QC_FRAMEWORK_FIG_EVENT,
        QC_FRAMEWORK_FIG_MASK,
        QC_FRAMEWORK_FIG_METRIC,
    ]
    RUNTIME_BENCHMARK_FILES += [
        BENCH_BASELINE_BAM_UNIFORMITY_QC,
        BENCH_AGGREGATE_BASELINE_QC,
        BENCH_BASELINE_MULTISCALE_BAM_UNIFORMITY_QC,
        BENCH_BASELINE_QC_REVIEW,
    ]
    RUNTIME_BENCHMARK_FILES += expand(BENCH_AGGREGATE_BASELINE_QC_MULTISCALE, bin_label=BASELINE_QC_BIN_LABELS)
    RUNTIME_BENCHMARK_FILES += expand(BENCH_BASELINE_SAMPLE_SAMTOOLS_DIAGNOSTICS, sample=BASELINE_SAMPLE_IDS)
if "reference_qc" in REQUESTED_TARGETS and TUNING_ENABLED:
    if BUILD_REF_BY_SEX_ENABLED:
        REFERENCE_QC_TARGET_FILES += [REF_SET_SAMPLE_LISTS[ref_set] for ref_set in REF_SET_ORDER]
        REFERENCE_QC_TARGET_FILES += [
            p
            for ref_set in REF_SET_ORDER
            for sex in REF_SEXES
            for prefilter_dir in [REF_SET_PREFILTER_DIR_BY_SEX[ref_set][sex]]
            for p in [
                str(Path(prefilter_dir) / "reference_sample_qc.tsv"),
                str(Path(prefilter_dir) / "reference_sample_qc.svg"),
                str(Path(prefilter_dir) / "reference_inlier_samples.txt"),
                str(Path(prefilter_dir) / "prefilter_summary.yaml"),
            ]
        ]
        REFERENCE_QC_TARGET_FILES += [
            p
            for ref_set in REF_SET_ORDER
            for p in [
                REF_SET_PREFILTER_MERGED_INLIERS[ref_set],
                REF_SET_TUNING_SUMMARY[ref_set],
                REF_SET_TUNING_BINSIZE_SUMMARY[ref_set],
                REF_SET_TUNING_BEST[ref_set],
                REF_SET_TUNING_QC[ref_set],
                REF_SET_TUNING_PLOT[ref_set],
                REF_SET_TUNING_QC_STATS_PLOT[ref_set],
                REF_SET_TUNING_INLIERS[ref_set],
                REF_SET_COMMON_BINSIZE[ref_set],
            ]
        ]
        RUNTIME_BENCHMARK_FILES += [BENCH_SELECT_REFERENCE_COHORT[ref_set] for ref_set in REF_SET_ORDER]
        RUNTIME_BENCHMARK_FILES += [
            BENCH_REFERENCE_PREFILTER_BY_SET_SEX[ref_set][sex]
            for ref_set in REF_SET_ORDER
            for sex in REF_SEXES
        ]
        RUNTIME_BENCHMARK_FILES += [BENCH_TUNE_WISECONDORX_REFERENCE_QC_BY_SET[ref_set] for ref_set in REF_SET_ORDER]
    else:
        REFERENCE_QC_TARGET_FILES += [TUNING_SUMMARY, TUNING_BINSIZE_SUMMARY, TUNING_BEST, TUNING_QC, TUNING_PLOT, TUNING_QC_STATS_PLOT, TUNING_INLIERS]
        REFERENCE_QC_TARGET_FILES += [
            str(Path(REF_PREFILTER_DIR) / "reference_sample_qc.tsv"),
            str(Path(REF_PREFILTER_DIR) / "reference_sample_qc.svg"),
            str(Path(REF_PREFILTER_DIR) / "reference_inlier_samples.txt"),
            str(Path(REF_PREFILTER_DIR) / "prefilter_summary.yaml"),
        ]
        RUNTIME_BENCHMARK_FILES += [
            BENCH_REFERENCE_PREFILTER,
            BENCH_TUNE_WISECONDORX_REFERENCE_QC,
        ]
    ALL_TARGET_FILES += REFERENCE_QC_TARGET_FILES
if "reference" in REQUESTED_TARGETS:
    ALL_TARGET_FILES += REF_TARGET_FILES
    REFERENCE_ASSET_TARGET_FILES += [
        REFERENCE_ATOMIC_BINS,
        REFERENCE_ANALYSIS_BINS,
        REFERENCE_QC_BINS,
        REFERENCE_ATOMIC_BIN_ANNOTATIONS,
        REFERENCE_ANALYSIS_BIN_ANNOTATIONS,
        REFERENCE_QC_BIN_ANNOTATIONS,
        REFERENCE_BIN_SUMMARY_JSON,
        REFERENCE_HARD_MASK_TSV,
        REFERENCE_SOFT_MASK_TSV,
        REFERENCE_DYNAMIC_MASK_TSV,
        REFERENCE_COMBINED_MASK_TSV,
        REFERENCE_HARD_MASK_JSON,
        REFERENCE_SOFT_MASK_JSON,
        REFERENCE_DYNAMIC_MASK_JSON,
        REFERENCE_COMBINED_MASK_JSON,
        REFERENCE_MASK_SUMMARY_JSON,
    ]
    REFERENCE_PACKAGE_TARGET_FILES += [
        REFERENCE_PACKAGE_MANIFEST,
        REFERENCE_PACKAGE_INVENTORY,
        REFERENCE_PACKAGE_README,
        REFERENCE_PACKAGE_DONE,
    ]
    if BUILD_REF_BY_SEX_ENABLED:
        RUNTIME_BENCHMARK_FILES += [
            BENCH_BUILD_REFERENCE_BY_SET_SEX[ref_set][sex]
            for ref_set in REF_SET_ORDER
            for sex in REF_SEXES
        ]
        RUNTIME_BENCHMARK_FILES += [BENCH_BUILD_GENDER_REFERENCE_BY_SET[ref_set] for ref_set in REF_SET_ORDER]
    else:
        RUNTIME_BENCHMARK_FILES.append(BENCH_BUILD_REFERENCE)
if "cnv_qc" in REQUESTED_TARGETS and CNV_ENABLED:
    ALL_TARGET_FILES += expand(CNV_QC_TSV, sample=SAMPLES) + expand(CNV_QC_PLOT, sample=SAMPLES)
    RUNTIME_BENCHMARK_FILES += expand(BENCH_WISECONDORX_CONVERT_FOR_CNV, sample=SAMPLES)
    RUNTIME_BENCHMARK_FILES += expand(BENCH_WISECONDORX_QC_FOR_PREDICT, sample=SAMPLES)
    if PREDICT_BY_SEX_ENABLED:
        RUNTIME_BENCHMARK_FILES += expand(BENCH_WISECONDORX_GENDER_FOR_PREDICT, sample=SAMPLES)
if "cnv" in REQUESTED_TARGETS and CNV_ENABLED:
    if CNV_POSTPROCESS_PRESERVE_BRANCH_A:
        ALL_TARGET_FILES += expand(CNV_DONE, sample=SAMPLES)
    if CNV_POSTPROCESS_ENABLE_BRANCH_B:
        REFERENCE_ASSET_TARGET_FILES += [
            REFERENCE_ANALYSIS_BIN_ANNOTATIONS,
            REFERENCE_COMBINED_MASK_TSV,
        ]
        ALL_TARGET_FILES += expand(CNV_B_FINAL_EVENTS, sample=SAMPLES)
        ALL_TARGET_FILES += expand(CNV_B_ARTIFACT_SUMMARY, sample=SAMPLES)
        ALL_TARGET_FILES += expand(CNV_B_FINAL_JSON, sample=SAMPLES)
    RUNTIME_BENCHMARK_FILES += expand(BENCH_WISECONDORX_PREDICT_CNV, sample=SAMPLES)
if "cnv_eval" in REQUESTED_TARGETS and CNV_ENABLED:
    ALL_TARGET_FILES += [CNV_EVAL_SAMPLE_METRICS, CNV_EVAL_EVENT_METRICS, CNV_EVAL_CALIBRATION, CNV_EVAL_SUMMARY]
if "cnv_ml" in REQUESTED_TARGETS and CNV_ENABLED:
    ALL_TARGET_FILES += [CNV_ML_FEATURES, CNV_ML_CV_METRICS, CNV_ML_CALIBRATION, CNV_ML_IMPORTANCE, CNV_ML_PREDICTIONS, CNV_ML_SUMMARY]
if "cnv_benchmark" in REQUESTED_TARGETS and CNV_ENABLED:
    ALL_TARGET_FILES += [CNV_BENCHMARK_SIMULATION, CNV_BENCHMARK_ADMIXTURE, CNV_BENCHMARK_SUMMARY]
if "cnv_report" in REQUESTED_TARGETS and CNV_ENABLED:
    ALL_TARGET_FILES += [CNV_REPORT_TSV, CNV_REPORT_JSON, CNV_REPORT_MD, CNV_REPORT_HTML]
if CNV_ENABLED and CNV_MOSAIC_FRACTION_TRUTH_TSV and REQUESTED_TARGETS & {"cnv_benchmark", "cnv_report"}:
    ALL_TARGET_FILES += [CNV_MOSAIC_TRUTH_VALIDATION_SUMMARY]

ALL_TARGET_FILES += REFERENCE_ASSET_TARGET_FILES
ALL_TARGET_FILES += REFERENCE_PACKAGE_TARGET_FILES
ALL_TARGET_FILES += QC_FRAMEWORK_TARGET_FILES

RUNTIME_TRACKING_INPUT_FILES = list(dict.fromkeys(ALL_TARGET_FILES))

if RUNTIME_TRACKING_ENABLED and RUNTIME_BENCHMARK_FILES:
    ALL_TARGET_FILES += [RUNTIME_DB, RUNTIME_TRACKING_SENTINEL]
